### ISSUE TITLE
Add `Registry` into `auto-id`

### ISSUE THREAD

**Issue by abhi3700** [subspace/auto-sdk#17]
Add Registry module to `@autonomys/auto-id` and an example showing how to register an auto-id.

```[tasklist]
### Tasks
- [x] Create a Registry class
- [x] Composes an extrinsic and calls the registry module
- [x] Register a certificate in the registry.
- [x] Example of registering an auto ID of issuer & user.
- [x] Test on Devnet (with auto-id domain)
```

**Comment by abhi3700** [comment]
WIP on [`fix-issue-17`](https://github.com/subspace/auto-sdk/tree/fix-issue-17) branch
