### ISSUE TITLE
Add `Registry` into `auto-id` Pt 2

### ISSUE THREAD

**Issue by abhi3700** [subspace/auto-sdk#48]
Add main functions:

- [x] revoke certificate
- [x] deactivate auto-id
- [x] renew auto-id

```[tasklist]
### Tasks
- [x] renew-self
- [x] renew-leaf
- [x] deactivate
- [x] revoke-self
- [x] revoke-leaf
- [x] More examples, Helpers, Utils
```
